### ISSUE TITLE
Custom element not found

### ISSUE THREAD

**Issue by filipjurik** [karlis-vagalis/circular-timer-card#1]
Hi,

I tried your card, but the display ends with an error.
_Custom element not found: circular-timer-card_
It is installed from HACS and the paths in resources are set correctly.
what is wrong?

**Comment by ggflempire** [comment]
Same for me. Tried to install it manually too without HACS

**Comment by eddysteurs** [comment]
same for me

**Comment by poudenes** [comment]
Maybe an overload. But same here. Installed via HACS. The resource is added. Clear cache. Nothing helped

**Comment by filipjurik** [comment]
redownloaded, reinstalled, clear cache, and no change.

**Comment by karlis-vagalis** [comment]
> redownloaded, reinstalled, clear cache, and no change.

Does the HACS indicate `154990b` commit as the installed/available one (very top left corner of the HACS page)? I tried installing the card via HACS myself and I needed to clear cache serveral times, after which everything did start correctly.

**Comment by filipjurik** [comment]
yes, I tried in another browser and it works. still not in the ios app

**Comment by eddysteurs** [comment]
works for me now, also in ios app, thx
