### ISSUE TITLE
HA 2024.12.4: custom element doesn't exist: circular-timer-card

### ISSUE THREAD

**Issue by misterbond007** [karlis-vagalis/circular-timer-card#18]
In HA 2024.12.4 this integration doesn't work any longer:
Custom element doesn't exist: circular-timer-card
Tried to uninstall and install from HACS again, same error.

**Comment by misterbond007** [comment]
Ok, just needed one more restart of Home Assistant. Now it works.

**Comment by brain-wash** [comment]
I restarted home assistant 10 times, cleared the cache the same amount of times, restarted firefox a bunch of times and even restarted my PC .. I still can't find the circular-timer-card. Reinstalling also did not help.
