### ISSUE TITLE
Custom card will not load

### ISSUE THREAD

**Issue by jmc5105** [karlis-vagalis/circular-timer-card#5]
This card is beautiful and I definitely want to use it. Unfortunately, the custom card will not load.

**Comment by karlis-vagalis** [comment]
Could you please provide more details and context? Did it work and now it does not? What do the browser console logs say?

**Comment by thomluther** [comment]
I have an issue with the card as well when using Firefox for the UI. It loads only in the companion app and Edge. So it may be browser dependent whether the card loads or not. In FF I just see ‘custom element does not exist’ for this particular card, although I restarted the browser and system multiple times, so it cannot be a caching issue.
It is actually the only card where I see this type of issue in FF and I use a lot of various custom cards.
In the console I cannot see any obvious error, but I'm not a web developper to really debug this browser error.

**Comment by Node815** [comment]
My setup:
![image](https://github.com/karlis-vagalis/circular-timer-card/assets/20736534/e424a33e-6a5a-4f6b-a16a-87b97efe95a1)
After saving this and even restarting Home Assistant I get the following:

![image](https://github.com/karlis-vagalis/circular-timer-card/assets/20736534/54320a2c-f15c-43c4-ba2b-d85ccbfac848)

Companion App (Android), Firefox and Vivaldi browser all show the same thing:
![image](https://github.com/karlis-vagalis/circular-timer-card/assets/20736534/5887e1b6-7086-4169-abfc-98055acb9dfc)

**Comment by thomluther** [comment]
> My setup: ![image](https://private-user-images.githubusercontent.com/20736534/291404167-e424a33e-6a5a-4f6b-a16a-87b97efe95a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Njk4NjEsIm5iZiI6MTcwMjk2OTU2MSwicGF0aCI6Ii8yMDczNjUzNC8yOTE0MDQxNjctZTQyNGEzM2UtNmE1YS00ZjZiLWExNmEtODdiOTdlZmU5NWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3MDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGU4NGI4OGE3NDM2ZGFiMTRhYjhiMjU3ZDA5ZDQ2NzZmZGViYTFkMGQ5MzZkNTU4NDVjOTY0MjNmMDBkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N9pjyjja9999WdjKK8tW2XpqWBeOr7BgPlcEacNBCJ4) After saving this and even restarting Home Assistant I get the following:
> 
> ![image](https://private-user-images.githubusercontent.com/20736534/291404744-54320a2c-f15c-43c4-ba2b-d85ccbfac848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Njk4NjEsIm5iZiI6MTcwMjk2OTU2MSwicGF0aCI6Ii8yMDczNjUzNC8yOTE0MDQ3NDQtNTQzMjBhMmMtZjE1Yy00M2M0LWJhMmItZDg1Y2NiZmFjODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3MDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NGMyYmRmNWMyMzEyZTY5ZmE1MTVmMDMzNDFjNmVkYmZhNmJlOTg5YmNkN2YzZTRlNTE4ODBjNjIyNTQwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dfH3Kd0xh-JevXUPXeTmIC3H4s6OQrBCgOb7KpIePNk)
> 
> Companion App (Android), Firefox and Vivaldi browser all show the same thing: ![image](https://private-user-images.githubusercontent.com/20736534/291405089-5887e1b6-7086-4169-abfc-98055acb9dfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Njk4NjEsIm5iZiI6MTcwMjk2OTU2MSwicGF0aCI6Ii8yMDczNjUzNC8yOTE0MDUwODktNTg4N2UxYjYtNzA4Ni00MTY5LWFiZmMtOTgwNTVhY2I5ZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3MDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDc0NzU5OGE0ODU2OThiZjViYTZkNGNkMzQyM2E1MWQyZjJhODc5MTY5NDI3MjUwMDAwNTNhZmI1YjRmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXlbK83_wQ86ebdOP1knwRFU3ZCsHK8POmQM1GO5HbA)
> 
> **Edit** To add that my installation method was via HACS

This looks more like you have not defined the timer.single entity. You need a valid timer entity to be displayed in the card.

**Comment by Node815** [comment]
Thanks!  I've never worked with timers in Home Assistant this way so I didn't realize I needed to define it in my configuration.yaml first.  I got it running as expected after I did this.

**Comment by karlis-vagalis** [comment]
Closed due to inactivity
